## 🔹 Block of Code  

A block of code is a group of one or more statements enclosed together, typically inside curly braces `{}` in languages like C, C++, Java, and JavaScript, or defined by indentation in Python.  

It represents a unit of execution, such as the body of a function, loop, or conditional statement.  

## 🔹 Python Indentation  

Python uses **indentation** (typically **four spaces**) to define code blocks. Unlike other languages that use `{}` or keywords, indentation in Python is **mandatory** as it determines the **scope and grouping** of statements.  

In [1]:
def check_blood_pressure(systolic, diastolic):
    # Function block
    if systolic < 120 and diastolic < 80:
        # If block
        status = "Normal"
    elif systolic < 130 and diastolic < 80:
        # Elif block
        status = "Elevated"
    else:
        # Else block
        status = "High"
    
    # Back to function block
    return status

# Main block
bp_reading = check_blood_pressure(128, 75)
print(f"Blood pressure status: {bp_reading}")

Blood pressure status: Elevated


### **Function Blocks**

In [ ]:
def greet_patient(name):
    # Function block
    return f"Hello, {name}. How are you feeling today?"

### **Conditional Blocks**

In [ ]:
temperature = 38.2
if temperature > 37.5:
    # Conditional block
    print("Patient has a fever")
else:
    # Another conditional block
    print("Temperature is normal")

### **Loop Blocks**

In [ ]:
for medication in ['aspirin', 'ibuprofen', 'acetaminophen']:
    # Loop block
    print(f"Check if patient has allergy to {medication}")

### **Exception Handling Blocks**

In [ ]:
try:
    # Try block
    heart_rate = int(input("Enter heart rate: "))
except ValueError:
    # Exception block
    print("Please enter a valid number")
finally:
    # Finally block
    print("Vital sign check complete")

# **Control Structures**

# 🔹 Sequential Structure  
- 📜 This is the default flow where code executes line by line  
- ⚙️ Built into Python's core functionality  

# 🔹 Decision/Selection Structure  
- ✅ The `if` statement for single condition checking  
- 🔀 The `if/else` statement for binary decisions  
- 🔄 The `if/elif/else` statement for multiple condition checking  

# 🔹 Repetition/Iterative Structure  
- 🔁 The `while` loop for condition-based repetition  
- 🔂 The `for` loop for sequence-based iteration  

### 🔹 Sequential Structure

In [1]:
print("Step 1: Starting patient intake")
patient_name = "Jane Smith"
print("Step 2: Recorded patient name:", patient_name)
temperature = 37.2
print("Step 3: Measured temperature:", temperature, "°C")
pulse = 72
print("Step 4: Recorded pulse rate:", pulse, "bpm")
patient_summary = f"Patient {patient_name} has temperature of {temperature}°C and pulse of {pulse} bpm."
print("Step 5: Generated patient summary")
print(patient_summary)
print("Step 6: Patient intake complete")

Step 1: Starting patient intake
Step 2: Recorded patient name: Jane Smith
Step 3: Measured temperature: 37.2 °C
Step 4: Recorded pulse rate: 72 bpm
Step 5: Generated patient summary
Patient Jane Smith has temperature of 37.2°C and pulse of 72 bpm.
Step 6: Patient intake complete


### 🔹 Decision/Selection Structure 

# 🔄 Python Comparison Operators 🐍  

Comparison operators in Python are used to compare **two values**. These operators return `True` or `False` based on the condition.  

## 📌 List of Comparison Operators  

| Operator | Description | Example |
|----------|------------|---------|
| `==`  | Equal to | `5 == 5` → `True` |
| `!=`  | Not equal to | `5 != 3` → `True` |
| `>`   | Greater than | `10 > 3` → `True` |
| `<`   | Less than | `3 < 10` → `True` |
| `>=`  | Greater than or equal to | `5 >= 5` → `True` |
| `<=`  | Less than or equal to | `4 <= 5` → `True` |

---

## 🔹 Logical Operators  

| Operator | Description | Example |
|----------|------------|---------|
| `and`  | Returns `True` if both conditions are `True` | `(5 > 2) and (3 < 4)` → `True` |
| `or`   | Returns `True` if at least one condition is `True` | `(5 > 2) or (3 > 4)` → `True` |
| `not`  | Negates the condition | `not (5 > 2)` → `False` |

---

## 🔹 Identity Operators  

| Operator | Description | Example |
|----------|------------|---------|
| `is`     | Returns `True` if two variables reference the same object | `a is b` |
| `is not` | Returns `True` if two variables reference different objects | `a is not b` |

---

## 🔹 Membership Operators  

| Operator | Description | Example |
|----------|------------|---------|
| `in`     | Returns `True` if a value is in a sequence | `"a" in "apple"` → `True` |
| `not in` | Returns `True` if a value is not in a sequence | `"x" not in "apple"` → `True` |

---

## 🎯 Example Usage  

```python
a = 10
b = 5

print(a == b)  # False ❌
print(a != b)  # True ✅
print(a > b)   # True ✅
print(a < b)   # False ❌
print(a >= 10) # True ✅
print(b <= 5)  # True ✅


# 🔄 Difference Between `=` and `==` in Python 🐍  

In Python, `=` and `==` are **not the same**! Many beginners make the mistake of using one instead of the other. Let’s break down the difference:  

---

## 📌 `=` (Assignment Operator)  
The `=` operator is used to **assign a value** to a variable.  

### 🎯 Example:  
```python
x = 10  # Assigns 10 to x
name = "Moses"  # Assigns "Moses" to name

print(x)  # Output: 10
print(name)  # Output: Moses


## 📌 `==` (Equality Operator)  

The `==` operator is used to **compare two values** and returns `True` if they are equal, otherwise `False`.  

## 🐍 Python `if-else` Statement 🚀  

The `if-else` statement in Python is used for **decision-making**. It allows the program to execute a block of code **only if** a certain condition is met.  

### 📌 Syntax:  

```python
if test_expression:
    # Body of if
else:
    # Body of else


In [3]:
age = 5

if age >= 18:
    print("You are an adult")

In [5]:
age = 5

if age >= 18:
    print("You are an adult")
else:
    print("You are not an adult")

You are not an adult


### 🔄 The `if/elif/else` Statement for Multiple Condition Checking

In medical decision-making, the `if/elif/else` statement is useful for diagnosing conditions based on symptoms or test results.  

#### 📌 How It Works:  
- The `if` condition checks the most critical or specific case first.  
- If `if` is `False`, `elif` conditions check other possibilities.  
- If none of the conditions match, the `else` block provides a general or alternative diagnosis.  

#### 🏥 Example: Diagnosing Fever Causes  


In [6]:
temperature = 39  # in Celsius

if temperature >= 40:
    print("🚨 High fever! Possible severe infection. Seek urgent care.")
elif 38 <= temperature < 40:
    print("🤒 Moderate fever. Could be flu or viral infection.")
elif 37 <= temperature < 38:
    print("😌 Mild fever. Monitor symptoms and rest.")
else:
    print("✅ Normal temperature. No fever detected.")

🤒 Moderate fever. Could be flu or viral infection.


## 🔹 Repetition/Iterative Structure  

In programming, repetition (iteration) allows a block of code to run multiple times until a condition is met.  

### 🔁 Types of Loops:  
- **`while` loop** → Repeats as long as a condition is `True`.  
- **`for` loop** → Iterates over a sequence (list, range, etc.).

In [7]:
heart_rates = [72, 75, 78, 80]

for rate in heart_rates:
    print(f"📊 Heart rate recorded: {rate} BPM")

📊 Heart rate recorded: 72 BPM
📊 Heart rate recorded: 75 BPM
📊 Heart rate recorded: 78 BPM
📊 Heart rate recorded: 80 BPM


In [8]:
blood_pressure = 160  # Initial systolic BP (mmHg)
safe_level = 120  # Target systolic BP

while blood_pressure > safe_level:  # Loop runs while BP is too high
    print(f"⚠️ Blood Pressure: {blood_pressure} mmHg - Administering treatment...")
    blood_pressure -= 5  # Simulating gradual decrease after treatment

print("✅ Blood pressure is stable. Monitoring stopped.")

⚠️ Blood Pressure: 160 mmHg - Administering treatment...
⚠️ Blood Pressure: 155 mmHg - Administering treatment...
⚠️ Blood Pressure: 150 mmHg - Administering treatment...
⚠️ Blood Pressure: 145 mmHg - Administering treatment...
⚠️ Blood Pressure: 140 mmHg - Administering treatment...
⚠️ Blood Pressure: 135 mmHg - Administering treatment...
⚠️ Blood Pressure: 130 mmHg - Administering treatment...
⚠️ Blood Pressure: 125 mmHg - Administering treatment...
✅ Blood pressure is stable. Monitoring stopped.


In [9]:
while True:  # Potential infinite loop
    user_input = input("Enter 'quit' to exit: ")
    if user_input == 'quit':
        break
    print(f"You entered: {user_input}")
print("Loop exited")

Enter 'quit' to exit:  quit


Loop exited


# 🔹 `break` and `continue` in Loops  

In Python loops (`for` and `while`), we use **`break`** to exit a loop early and **`continue`** to skip the current iteration and move to the next one.

---

## ✅ **1. Using `break` (Exiting a Loop Early)**  
The `break` statement **immediately stops the loop** when a condition is met.

### 🏥 **Example: Stopping Patient Monitoring if a Critical Condition is Found**  

In [10]:
heart_rates = [72, 75, 150, 78, 80]  # Patient heart rates

for rate in heart_rates:
    if rate > 140:  # Critical condition detected
        print(f"🚨 Alert! Critical heart rate detected: {rate}")
        break  # Stop checking further
    print(f"✅ Normal heart rate: {rate}")

✅ Normal heart rate: 72
✅ Normal heart rate: 75
🚨 Alert! Critical heart rate detected: 150


## ✅ 2. Using `continue` (Skipping an Iteration)  

The `continue` statement skips the current iteration and moves to the next one.  

### 🏥 Example: Skipping Missing Data in Blood Pressure Readings  

In [11]:
bp_readings = [120, None, 130, 125, None, 140]  # Some missing values

for bp in bp_readings:
    if bp is None:  # Skip missing data
        continue  
    print(f"✅ Blood Pressure: {bp}")

✅ Blood Pressure: 120
✅ Blood Pressure: 130
✅ Blood Pressure: 125
✅ Blood Pressure: 140


# 🩺 **Python Control Structures Recap: Medical Case Study Quiz** 🚑🔬  

**Test your knowledge of conditional statements, decision-making, and loops with real-world medical scenarios!** 🧑‍⚕️💻  

In [12]:
###  What will be the output of the following code?  

pain_scale = 8  # Pain scale from 0-10

if pain_scale >= 9:
    print("🚨 Severe pain - Emergency care needed!")
elif pain_scale >= 5:
    print("⚠️ Moderate pain - Consider pain relief medication.")
else:
    print("🙂 Mild pain - Rest and monitor.")

⚠️ Moderate pain - Consider pain relief medication.


In [13]:
###  What will be the output of this while loop?

heart_rate = 110

if heart_rate > 120:
    print("🚨 Tachycardia detected!")
elif heart_rate > 100:
    print("⚠️ Elevated heart rate")
elif heart_rate > 60:
    print("✅ Normal heart rate")
else:
    print("⚠️ Bradycardia detected")

⚠️ Elevated heart rate


In [14]:
## What will be printed when the following code is executed?

patient_age = 70

if patient_age >= 65:
    print("🩺 Elderly patient - Regular health checks required")
elif patient_age >= 18:
    print("🙂 Adult patient - Maintain healthy lifestyle")
else:
    print("🧒 Child patient - Pediatric care needed")

🩺 Elderly patient - Regular health checks required


In [15]:
## What will be the output of this while loop?

temperature = 39

while temperature > 37:
    print(f"🌡️ Monitoring temperature: {temperature}°C")
    temperature -= 1

🌡️ Monitoring temperature: 39°C
🌡️ Monitoring temperature: 38°C


In [18]:
## How many times will this for loop run?

for i in range(5):
    print(f"💉 Administering medication {i}...")

💉 Administering medication 0...
💉 Administering medication 1...
💉 Administering medication 2...
💉 Administering medication 3...
💉 Administering medication 4...


In [19]:
## What will be the output of this for loop?
blood_pressures = [120, 135, 150, 165]

for bp in blood_pressures:
    if bp >= 140:
        print(f"⚠️ High blood pressure detected: {bp} mmHg")
    else:
        print(f"✅ Normal blood pressure: {bp} mmHg")

✅ Normal blood pressure: 120 mmHg
✅ Normal blood pressure: 135 mmHg
⚠️ High blood pressure detected: 150 mmHg
⚠️ High blood pressure detected: 165 mmHg


# 🐍 Introduction to Functions in Python 🚀  

## 🔹 What Are Functions?  
Functions in Python allow us to **reuse code** by encapsulating logic into a single unit. Instead of writing the same code multiple times, we define a function once and call it whenever needed.  

## 📌 Why Use Functions?  
✅ Improves code **reusability**  
✅ Enhances **readability** and **organization**  
✅ Makes debugging **easier**  
✅ Helps in **modular programming** 

---

## 🔹 Defining a Function in Python  
A function is defined using the `def` keyword:  

In [20]:
def greet():
    print("Hello! Welcome to Python Functions.")

## 🔹 Calling a Function  
To execute a function, we call it using its name followed by parentheses:  

In [21]:
greet()

Hello! Welcome to Python Functions.


## 🔹 Function with Parameters  
Parameters allow functions to accept inputs and process them.  

In [22]:
def greet_patient(name):
    print(f"Hello, {name}! How are you feeling today?")

In [24]:
greet_patient("Moses")  # Output: Hello, John! How are you feeling today?

Hello, Moses! How are you feeling today?


## 🔹 Function with Return Value  
A function can return a value using the `return` statement.  

In [25]:
def add_numbers(a, b):
    return a + b

In [29]:
result = add_numbers(5, 3)
print(result)  # Output: 8

8


## 🔹 Default Parameter Values  
If a parameter is not provided, a default value can be used.  

In [30]:
def check_temperature(temp=37):
    if temp > 37:
        return "Fever detected! 🔥"
    else:
        return "Normal temperature ✅"

In [31]:
print(check_temperature(39))  # Output: Fever detected! 🔥
print(check_temperature())    # Output: Normal temperature ✅

Fever detected! 🔥
Normal temperature ✅


## 🔹 Multiple Parameters  

A function can accept multiple parameters:

In [32]:
def calculate_bmi(weight, height):
    bmi = weight / (height ** 2)
    return f"Your BMI is {bmi:.2f}"

In [33]:
print(calculate_bmi(70, 1.75))  # Output: Your BMI is 22.86

Your BMI is 22.86


## 🔹 *args (Arbitrary Positional Arguments)  

The `*args` parameter allows a function to accept multiple positional arguments as a tuple.  

In [34]:
def average_heart_rate(*args):
    return sum(args) / len(args)

In [35]:
print(average_heart_rate(80, 85, 78, 90))  # Output: 83.25

83.25


In [36]:
def average_heart_rate(*args):
    print(args)

In [37]:
average_heart_rate(80, 85, 78, 90)

(80, 85, 78, 90)


## 🔹 **kwargs (Arbitrary Keyword Arguments)  

The `**kwargs` parameter allows a function to accept multiple keyword arguments as a dictionary.  

In [38]:
def patient_scan_info(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

In [39]:
patient_scan_info(name="Alice", age=45, scan_type="MRI", diagnosis="Brain Tumor")  
# Output:  
# name: Alice  
# age: 45  
# scan_type: MRI  
# diagnosis: Brain Tumor  

name: Alice
age: 45
scan_type: MRI
diagnosis: Brain Tumor


## 🔹 Lambda (Anonymous) Functions  

A lambda function is a small anonymous function defined in a single line.  


In [40]:
square = lambda x: x ** 2
print(square(5))  # Output: 25

25


In [41]:
fever_check = lambda temp: "Fever! 🔥" if temp > 37 else "Normal ✅"
print(fever_check(38))  # Output: Fever! 🔥

Fever! 🔥


## 📝 Class Quiz: Functions in Python

In [42]:
### What will be the output of the following function call?  

def check_bp(systolic, diastolic=80):
    if systolic > 130 or diastolic > 90:
        return "High Blood Pressure 🚨"
    else:
        return "Normal Blood Pressure ✅"

print(check_bp(140))

High Blood Pressure 🚨


In [44]:
### There is an issue in the function below. Can you fix it?

def patient_record(**info):
    print("Patient Information:")
    for key, value in info.items():
        print(f"{key}: {value}")

patient_record(name="John", age=45, diagnosis="Pneumonia")

Patient Information:
name: John
age: 45
diagnosis: Pneumonia


In [45]:
### What will be the output of the following function call?

def scan_result(scan_type, severity="Mild"):
    return f"{scan_type} scan shows {severity} condition."

print(scan_result("CT", severity="Severe"))

CT scan shows Severe condition.


In [46]:
### What will be the output of the following function call?

def patient_info(**kwargs):
    return f"Patient: {kwargs['name']}, Age: {kwargs['age']}, Condition: {kwargs.get('condition', 'Not Diagnosed')}"

print(patient_info(name="Jane", age=50))

Patient: Jane, Age: 50, Condition: Not Diagnosed


# 📌 Introduction to NumPy  

## 🔹 What is NumPy?  
NumPy (Numerical Python) is a powerful library for numerical computing in Python. It provides efficient support for large, multi-dimensional arrays and mathematical functions.  

✅ **Why use NumPy?**  
- Faster computations compared to Python lists  
- Supports mathematical operations like addition, subtraction, and multiplication  
- Provides useful functions for statistics, linear algebra, and array manipulations  

---

## 🔹 NumPy Arrays  
NumPy uses **ndarrays (N-dimensional arrays)** for data storage and manipulation.

In [47]:
import numpy as np

In [49]:
my_list = [72, 80, 78, 85, 90]
my_list

[72, 80, 78, 85, 90]

In [48]:
### 🏥 **Example: Storing Patient Data**  

# Creating a 1D NumPy array for patient heart rates
heart_rates = np.array([72, 80, 78, 85, 90])

print(heart_rates)  # Output: [72 80 78 85 90]

[72 80 78 85 90]


## 🔹 Array Operations (Addition, Subtraction, Multiplication, etc.)  

NumPy allows direct mathematical operations on arrays.  


In [50]:
blood_pressure = np.array([120, 130, 110, 140])
adjusted_bp = blood_pressure + 5  # Increase all values by 5

print(adjusted_bp)  # Output: [125 135 115 145]

[125 135 115 145]


In [51]:

heart_rates_morning = np.array([72, 80, 78, 85])
heart_rates_evening = np.array([75, 82, 80, 88])

total_heart_rates = heart_rates_morning + heart_rates_evening

print(total_heart_rates)  # Output: [147 162 158 173]

[147 162 158 173]


In [52]:
before_medication = np.array([150, 180, 200, 170])
after_medication = np.array([130, 160, 175, 155])

glucose_reduction = before_medication - after_medication

print(glucose_reduction)  # Output: [20 20 25 15]

[20 20 25 15]


In [53]:
base_dosage = np.array([2, 5, 3, 4])  # Base mg of a drug
weight_factor = np.array([1.2, 1.5, 1.3, 1.4])  # Weight-based factor

adjusted_dosage = base_dosage * weight_factor

print(adjusted_dosage)  # Output: [2.4 7.5 3.9 5.6]

[2.4 7.5 3.9 5.6]


In [54]:
weights = np.array([70, 80, 65, 90])  # in kg
heights = np.array([1.75, 1.80, 1.60, 1.85])  # in meters

bmi = weights / (heights ** 2)

print(bmi)  # Output: [22.86 24.69 25.39 26.29]

[22.85714286 24.69135802 25.390625   26.29656684]


## 🔹 Matrix Multiplication (Dot Product)  

For more advanced operations, NumPy supports matrix multiplication.  

In [55]:
test_results = np.array([[90, 85], [75, 80]])  # Scores of two patients
weight_matrix = np.array([[0.6, 0.4], [0.7, 0.3]])  # Weight factors

predicted_scores = np.dot(test_results, weight_matrix)

print(predicted_scores)
# Output: [[84 80]
#          [77 75]]

[[113.5  61.5]
 [101.   54. ]]


## 🔹 Basic NumPy Operations (Min, Max, etc.)  

NumPy provides built-in functions to analyze data.  

## ✅ Useful Functions:  

`np.min(array)`, `np.max(array)`, `np.mean(array)`, `np.std(array)`, etc.  

In [56]:
glucose_levels = np.array([90, 110, 85, 150, 100])

print(np.min(glucose_levels))  # Output: 85 (Lowest glucose level)
print(np.max(glucose_levels))  # Output: 150 (Highest glucose level)
print(np.mean(glucose_levels)) # Output: Average glucose level

85
150
107.0


## 🔹 Array Slicing and Indexing  

NumPy allows efficient indexing and slicing for selecting data.  

In [57]:
patients = np.array(["Alice", "Bob", "Charlie", "David", "Emma"])

print(patients[1])     # Output: Bob (Selecting index 1)
print(patients[1:4])   # Output: ['Bob' 'Charlie' 'David'] (Slicing from index 1 to 3)

Bob
['Bob' 'Charlie' 'David']


In [60]:
temperatures = np.array([36.5, 37.2, 38.0, 39.1, 36.8])  # Body temperatures in Celsius

print(temperatures[0])  # Output: 36.5 (First element)
print(temperatures[-1]) # Output: 36.8 (Last element)

36.5
36.8


In [61]:
print(temperatures[1:4])   # Output: [37.2 38.0 39.1] (Index 1 to 3)
print(temperatures[:3])    # Output: [36.5 37.2 38.0] (First 3 elements)
print(temperatures[::2])   # Output: [36.5 38.0 36.8] (Every other element)

[37.2 38.  39.1]
[36.5 37.2 38. ]
[36.5 38.  36.8]


## 🔹 2D NumPy Indexing  

NumPy supports multi-dimensional indexing for structured data.  

## ✅ Uses in Medical Imaging:  

- Storing pixel values from CT/MRI scans  
- Analyzing medical image slices  

In [62]:
mri_scan = np.array([
    [0, 1, 2], 
    [3, 4, 5], 
    [6, 7, 8]
])

print(mri_scan[1, 2])   # Output: 5 (Row 1, Column 2)
print(mri_scan[:, 1])   # Output: [1 4 7] (All rows, Column 1)

5
[1 4 7]


## 🔹 Slicing in 2D Arrays

In 2D arrays, we use `array[row, column]` to access elements.  

In [63]:
mri_scan = np.array([
    [10, 20, 30, 40],  
    [50, 60, 70, 80],  
    [90, 100, 110, 120]  
])

print(mri_scan[1, 2])   # Output: 70 (Row 1, Column 2)
print(mri_scan[:, 1])   # Output: [20 60 100] (All rows, Column 1)
print(mri_scan[1, :])   # Output: [50 60 70 80] (Entire Row 1)

70
[ 20  60 100]
[50 60 70 80]


## 🔹 Boolean Indexing for Conditional Selection  

We can filter data based on conditions using Boolean indexing.  

### 🏥 Example: Identifying High Fever Patients  

In [64]:
fever_patients = temperatures[temperatures > 37.5]

print(fever_patients)  # Output: [38.  39.1] (Only patients with fever)

[38.  39.1]


## 🔹 Fancy Indexing (Selecting Multiple Elements)  

Fancy indexing allows us to select multiple elements at once using an array of indices.  

### 🏥 Example: Selecting Specific Patients' Heart Rates  

In [65]:
heart_rates = np.array([72, 80, 78, 85, 90])

selected_indices = [0, 2, 4]  
selected_heart_rates = heart_rates[selected_indices]

print(selected_heart_rates)  # Output: [72 78 90]

[72 78 90]


In [66]:
# Rows: Patients, Columns: Test Results (e.g., Blood Pressure, Glucose Level)
medical_tests = np.array([
    [120, 80, 90],   # Patient 1
    [130, 85, 88],   # Patient 2
    [110, 75, 85],   # Patient 3
    [140, 95, 92]    # Patient 4
])

print(medical_tests[1, :])  # Output: [130  85  88]  (Entire row for Patient 2)
print(medical_tests[:, 0])  # Output: [120 130 110 140] (All patients' Blood Pressure)

[130  85  88]
[120 130 110 140]


# 🧠 NumPy Recap Quiz 🎯  

Test your understanding of **NumPy** with these 5 coding challenges!  

---

In [67]:
## 1️⃣ **What will be the output of this NumPy operation?**  

import numpy as np  

arr = np.array([10, 20, 30, 40, 50])  
print(arr[1:4])  

[20 30 40]


In [69]:
## Which statement correctly selects all the rows of the second column in a 2D NumPy array?

import numpy as np  

data = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])

data[:, 1]


array([10, 25, 40])

🔘 **A)** `data[:, 1]`  
🔘 **B)** `data[1, :]`  
🔘 **C)** `data[1, 1]`  
🔘 **D)** `data[:, 2]`  

In [71]:
3️⃣ What will be the output of this array slicing operation?

arr = np.array([100, 200, 300, 400, 500])  
print(arr[::2])  

Object `operation` not found.
[100 300 500]


🔘 **A)** [100, 200, 300]  
🔘 **B)** [100, 300, 500]  
🔘 **C)** [200, 400]  
🔘 **D)** [100, 400]  

In [72]:
## 4️⃣ What does the following NumPy Boolean indexing operation return?

bp_readings = np.array([120, 135, 150, 110, 145])  
high_bp = bp_readings[bp_readings > 130]  
print(high_bp)

[135 150 145]


🔘 **A)** [135, 150, 145]  
🔘 **B)** [150, 145]  
🔘 **C)** [120, 135, 150]  
🔘 **D)** [110, 120]  

In [ ]:
## 5️⃣ Which NumPy function is used for element-wise multiplication of two arrays?

import numpy as np  

arr1 = np.array([2, 4, 6])  
arr2 = np.array([3, 5, 7])  

result = np.dot(arr1, arr2) # Fill in the missing function

🔘 **A)** `np.multiply(arr1, arr2)`  
🔘 **B)** `np.dot(arr1, arr2)`  
🔘 **C)** `np.add(arr1, arr2)`  
🔘 **D)** `np.prod(arr1, arr2)`  

# 🚀 Object-Oriented Programming (OOP)

(OOP) focuses on **breaking down a task** into units known as **objects**. Each object includes:

- 📊 **Variables (Data)** – Stores information related to the object.  
- ⚙️ **Subroutines (Methods)** – Defines the object's behavior and actions.  

By organizing code into **objects**, OOP enhances **modularity, reusability, and maintainability**. 🚀


A **class** acts as a **template or blueprint** for creating a specific set of objects.  

- 🏗 **Defines Structure** – Specifies attributes and methods for objects.  
- 🔄 **Reusable** – Multiple objects can be created from a single class.  
- 🎭 **General vs. Specific** – The class provides a general structure, while objects hold specific values.  


### **Class: Patient**  
- **Attributes** – Name, age, medical history, blood type.  
- **Methods** – Book appointment, take medication, request lab tests.  

Each **patient object** created from this class will have unique attribute values while following the same structure!

![Class](https://codersite.dev/assets/images/carClass.jpg)

## 🔹 **Key Principles of OOP**  

### 🏥 1️⃣ **Encapsulation** (Data Hiding & Protection)  
Encapsulation is the **bundling of data (variables) and methods (functions)** that operate on the data within a single unit (a class).  

- It **restricts direct access** to some details of an object, ensuring data security.  
- We use **private variables** (`_variable` or `__variable`) to hide data.  

📌 **Example: Patient Data Protection**  
```python
class Patient:
    def __init__(self, name, age, diagnosis):
        self.name = name  
        self.age = age  
        self.__diagnosis = diagnosis  # Private variable

    def get_diagnosis(self):
        return self.__diagnosis  # Accessing private data safely

patient1 = Patient("John Doe", 45, "Hypertension")
print(patient1.get_diagnosis())  # Output: Hypertension


## 🔹 `__init__` Method in Python Classes  

In Python, the `__init__` method is a special constructor method that automatically runs when an object is created. It initializes the attributes of the class.  

In [ ]:
class Patient:
    def __init__(self, name, age, diagnosis):
        self.name = name  # Patient's name
        self.age = age  # Patient's age
        self.diagnosis = diagnosis  # Medical condition

    def get_info(self):
        return f"Patient: {self.name}, Age: {self.age}, Diagnosis: {self.diagnosis}"

# Creating a patient object
patient1 = Patient("John Doe", 45, "Hypertension")

# Display patient details
print(patient1.get_info()) # Output: Patient: John Doe, Age: 45, Diagnosis: Hypertension

## 🔹 Understanding `self` in Python Classes  

In Python, `self` is a reference to the current instance of a class. It allows access to attributes and methods within the class.  

### ✅ Key Points About `self`  
- It must be the first parameter in instance methods (but you don’t pass it manually when calling the method).  
- It refers to the object itself, allowing interaction with its attributes and methods.  
- Each object of a class has its own separate `self`, ensuring unique data storage.  

In [73]:
class Patient:
    def __init__(self, name, age, diagnosis):
        self.name = name  # Assigns the name to the object
        self.age = age  # Assigns the age to the object
        self.diagnosis = diagnosis  # Assigns the diagnosis to the object

    def get_details(self):
        return f"Patient: {self.name}, Age: {self.age}, Diagnosis: {self.diagnosis}"

# Creating two patient objects
patient1 = Patient("Alice Brown", 35, "Pneumonia")
patient2 = Patient("John Doe", 50, "Diabetes")

# Displaying patient details
print(patient1.get_details())  
print(patient2.get_details())  

# Output:
# Patient: Alice Brown, Age: 35, Diagnosis: Pneumonia
# Patient: John Doe, Age: 50, Diagnosis: Diabetes

Patient: Alice Brown, Age: 35, Diagnosis: Pneumonia
Patient: John Doe, Age: 50, Diagnosis: Diabetes


## 🔥 How `self` Works Here  

1️⃣ When we create `patient1`, Python calls `__init__` with `self` referring to `patient1`.  
2️⃣ It stores `"Alice Brown"`, `35`, and `"Pneumonia"` inside `patient1`.  
3️⃣ The `get_details()` method uses `self.name`, `self.age`, and `self.diagnosis` to return details specific to that patient.  
4️⃣ The same process happens for `patient2`, but with different values.  

## 🧬 2️⃣ Inheritance (Code Reusability)  

Inheritance allows a class (child class) to derive properties and behavior from another class (parent class), promoting code reuse.  

In [ ]:
# Parent class (Base class)
class MedicalScan:
    def __init__(self, patient_name, resolution):
        self.patient_name = patient_name
        self.resolution = resolution

    def get_scan_info(self):
        return f"Patient: {self.patient_name}, Resolution: {self.resolution} DPI"



# Child class for CT Scans (inherits from MedicalScan)
class CTScan(MedicalScan):
    def __init__(self, patient_name, resolution, contrast_used):
        super().__init__(patient_name, resolution)  # Inherit common attributes
        self.contrast_used = contrast_used  # Unique attribute for CT scans

    def get_details(self):
        contrast_status = "Yes" if self.contrast_used else "No"
        return f"{self.get_scan_info()}, Scan Type: CT, Contrast Used: {contrast_status}"





# Child class for MRI Scans (inherits from MedicalScan)
class MRIScan(MedicalScan):
    def __init__(self, patient_name, resolution, magnetic_field_strength):
        super().__init__(patient_name, resolution)  # Inherit common attributes
        self.magnetic_field_strength = magnetic_field_strength  # Unique attribute for MRI scans

    def get_details(self):
        return f"{self.get_scan_info()}, Scan Type: MRI, Magnetic Field Strength: {self.magnetic_field_strength} Tesla"



# Creating objects for different scans
ct_scan = CTScan("Alice Brown", 512, True)
mri_scan = MRIScan("John Doe", 256, 3.0)

# Display scan details
print(ct_scan.get_details())  
print(mri_scan.get_details())

# Output:
# Patient: Alice Brown, Resolution: 512 DPI, Scan Type: CT, Contrast Used: Yes
# Patient: John Doe, Resolution: 256 DPI, Scan Type: MRI, Magnetic Field Strength: 3.0 Tesla

## 🧪 3️⃣ Polymorphism (Multiple Forms of Methods)  

Polymorphism allows different classes to have methods with the same name but different implementations.  

### 📌 Example: Different Medical Professionals Examining a Patient  

In [74]:
# Base Class
class MedicalSpecialist:
    def diagnose(self):
        return "Examining the patient..."

# Child Class 1: Radiologist
class Radiologist(MedicalSpecialist):
    def diagnose(self):
        return "Reviewing X-rays and MRI scans to detect abnormalities."

# Child Class 2: Cardiologist
class Cardiologist(MedicalSpecialist):
    def diagnose(self):
        return "Interpreting ECG results and diagnosing heart conditions."

# Child Class 3: Neurologist
class Neurologist(MedicalSpecialist):
    def diagnose(self):
        return "Assessing brain scans and neurological functions."

# Using polymorphism
def perform_diagnosis(specialist):
    print(specialist.diagnose())

# Instantiate objects
specialists = [Radiologist(), Cardiologist(), Neurologist()]
for doctor in specialists:
    perform_diagnosis(doctor)

# Output:
# Reviewing X-rays and MRI scans to detect abnormalities.
# Interpreting ECG results and diagnosing heart conditions.
# Assessing brain scans and neurological functions.

Reviewing X-rays and MRI scans to detect abnormalities.
Interpreting ECG results and diagnosing heart conditions.
Assessing brain scans and neurological functions.


## 🔬 4️⃣ Abstraction (Hiding Complexity)  

Abstraction means hiding complex implementation details and exposing only essential features.  

### 📌 Example: Abstracting a Medical Device  

In [75]:
from abc import ABC, abstractmethod

class MedicalDevice(ABC):  
    @abstractmethod
    def operate(self):
        pass  # Abstract method

class ECGMonitor(MedicalDevice):
    def operate(self):
        return "Recording heart electrical activity."

class MRI_Scanner(MedicalDevice):
    def operate(self):
        return "Generating detailed images of the body."

device = MRI_Scanner()
print(device.operate())  # Output: Generating detailed images of the body.

Generating detailed images of the body.


# 📚 Additional Resources on Python OOP (Classes & Inheritance)

## 📖 Official Documentation & Guides  
1. **Python Classes & Objects (Official Docs)**  
   🔗 [https://docs.python.org/3/tutorial/classes.html](https://docs.python.org/3/tutorial/classes.html)  

2. **Real Python: Object-Oriented Programming in Python**  
   🔗 [https://realpython.com/python3-object-oriented-programming/](https://realpython.com/python3-object-oriented-programming/)  

3. **GeeksforGeeks: Python OOP Explained**  
   🔗 [https://www.geeksforgeeks.org/python-oops-concepts/](https://www.geeksforgeeks.org/python-oops-concepts/)  

---

## 🎥 Video Tutorials on OOP in Python  
1. **Python OOP in One Video (CodeWithHarry)** – YouTube  
   🔗 [https://www.youtube.com/watch?v=JeznW_7DlB0](https://www.youtube.com/watch?v=JeznW_7DlB0)  

2. **Python OOP Tutorial for Beginners (Programming with Mosh)** – YouTube  
   🔗 [https://www.youtube.com/watch?v=Ej_02ICOIgs](https://www.youtube.com/watch?v=Ej_02ICOIgs)  

3. **CS Dojo – Python Classes and Objects**  
   🔗 [https://www.youtube.com/watch?v=ZDa-Z5JzLYM](https://www.youtube.com/watch?v=ZDa-Z5JzLYM)  

---

## 📘 Books for Deeper Learning  
1. **"Python Crash Course" by Eric Matthes** – Great for beginners, covers OOP well.  
   🔗 [https://nostarch.com/python-crash-course-2nd-edition](https://nostarch.com/python-crash-course-2nd-edition)  

2. **"Fluent Python" by Luciano Ramalho** – Advanced concepts, including OOP, for Pythonistas.  
   🔗 [https://www.oreilly.com/library/view/fluent-python-2nd/9781492056348/](https://www.oreilly.com/library/view/fluent-python-2nd/9781492056348/)  

3. **"Automate the Boring Stuff with Python" by Al Sweigart** – Practical examples, including OOP.  
   🔗 [https://automatetheboringstuff.com/](https://automatetheboringstuff.com/)  

---

## 🛠 Hands-on Practice & Interactive Learning  
1. **W3Schools – Python OOP Interactive Guide**  
   🔗 [https://www.w3schools.com/python/python_classes.asp](https://www.w3schools.com/python/python_classes.asp)  

2. **LeetCode OOP Challenges** (Great for practice!)  
   🔗 [https://leetcode.com/problemset/all/](https://leetcode.com/problemset/all/) (Search "Object-Oriented")  

3. **HackerRank Python OOP Challenges**  
   🔗 [https://www.hackerrank.com/domains/tutorials/10-days-of-oop](https://www.hackerrank.com/domains/tutorials/10-days-of-oop)  